[package]
name = "animals_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
csv = "1.3.0"
text_io = "0.1.12"
regex = "1.10.4"
tempfile = "3.10.1"